version: '3'

services:
  presentation:
    container_name: presentation
    image: presentation
    build:
      context: source
      dockerfile: presentation/Dockerfile
    volumes:
      - ./source/packages:/packages
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
      - otel-collector
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  listener:
    container_name: listener
    image: listener
    build:
      context: source
      dockerfile: listener/Dockerfile
    volumes:
      - ./source/packages:/packages
    ports:
      - '8090:8090'
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  mongo:
    container_name: mongo
    image: mongo:7.0
    command: mongod --bind_ip_all --port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pix
      - MONGO_INITDB_ROOT_PASSWORD=N5Hn3cHgeP27JGlt7g4ASy6O8zXLNm228sjKxEn8
      - "TZ=America/Sao_Paulo"
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb/data:/data/db
      - ./configuration/mongodb/init.db.js:/docker-entrypoint-initdb.d/init.js:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        window: 120s

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/loki/loki-local.yaml
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./configuration/loki/loki.yaml:/etc/loki/loki-local.yaml
      - ./volumes/loki:/tmp/loki
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  grafana:
    image: grafana
    container_name: grafana
    restart: always
    build: configuration/grafana
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=pix
      - GF_SECURITY_ADMIN_PASSWORD=bj0uIVfZAj7O5y94gC1yVPStPfw5xFxQpburWjvUIgnYeFxs7L
      - "TZ=America/Sao_Paulo"
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: always
    command:
      - --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./configuration/otel-collector/otel-collector.yml:/etc/otelcol-cont/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - tempo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s


  tempo:
    container_name: tempo
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configuration/tempo/tempo.yaml:/etc/tempo.yaml
      - ./volumes/tempo:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
    environment:
      - "TZ=America/Sao_Paulo"
    depends_on:
      - tempo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configuration/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s

  rabbitmq:
    image: rabbitmq:3.12.8-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=pix
      - RABBITMQ_DEFAULT_PASS=ZiU42veV7Ud48A0dyb9ASgYsHbR6Un
      - RABBITMQ_MESSAGE_TTL=3600000
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
