global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'presentation'
    static_configs:
      - targets: [ 'presentation:8080' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'listener'
    static_configs:
      - targets: [ 'listener:8090' ]
    metrics_path: '/actuator/prometheus'